// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Todo.Data;

#nullable disable

namespace Todo.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20241103142142_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Todo.Data.Entity.TodoItem", b =>
                {
                    b.Property<string>("ID")
                        .HasMaxLength(36)
                        .HasColumnType("nchar(36)");

                    b.Property<string>("Comments")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("Completed")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("ID");

                    b.ToTable("TodoItems");

                    b.HasData(
                        new
                        {
                            ID = "6bb8a868-dba1-4f1a-93b7-24ebce87e243",
                            Comments = "Maybe take Coursera Courses too?",
                            Completed = true,
                            Name = "Learn app development",
                            Notes = "Take Microsoft Learn Courses"
                        },
                        new
                        {
                            ID = "b94afb54-a1cb-4313-8af3-b7511551b33b",
                            Comments = "Maybe use Visual Studio Code instead?",
                            Completed = false,
                            Name = "Develop apps",
                            Notes = "Use Visual Studio and Visual Studio for Mac"
                        },
                        new
                        {
                            ID = "ecfa6f80-3671-4911-aabe-63cc442c1ecf",
                            Completed = false,
                            Name = "Publish apps",
                            Notes = "All app stores"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
